import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>HELLO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          READ 
          <Link href="/posts/first-post">
            <a>THIS PAGE</a>
          </Link>
        </h1>

        <Image 
          src="/images/300-pepe01.png"
          width={300}
          height={300}
          alt='pepe'
        />
      </main>
    </div>
  )
}
